blog_on_rails_part2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :comments
  end

  resources :users do
    get('password', {to: "users#change_password"})
    post('password', {to: "users#change_password"})
  end

 

  resource :session, only:[:new, :create, :destroy]
end

blog_on_rails_part2/app/views/shared/_alert.html.erb
<% if flash[:notice].present?%>
<div class="alert alert-success alert-dismissable fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>

<% elsif flash[:alert].present?%>
<div class="alert alert-warning alert-dismissable fade show" role="alert">
    <%= flash[:alert]%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span></button>
</div>
<% end %>

blog_on_rails_part2/app/views/shared/_form.html.erb
<div class="container mt-4">
<%= form_with model: @post, :class=>"form-group", local:true do |f|%>
    <%if @post.errors.any?%>
        <p class="text-danger"><%= @post.errors.full_messages.join(", ")%></p>
    <%end%>
    <%= f.label :title%>
    <div class="input-group">
        
        <%= f.text_field :title, :class=>'form-control mb-4', :required=>true%>
    </div>
    <%= f.label :body%>
    <div class="input-group">
        <%= f.text_area :body, cols:50 , rows:5,  :class=>'form-control', :required=>true %>
    </div>
    <div class="d-flex justify-content-center">
        <div class="mr-2">
        <%= f.submit :class => 'btn btn-outline-primary mt-4'%>
        </div>
        <div class="ml-2">
            <%= link_to("Cancel", root_path, :class => 'btn btn-outline-primary mt-4')%>
        </div>
    </div>
<%end%>
</div>

blog_on_rails_part2/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
<div class="navbar-brand">
    <%= link_to("Blog On Rails", root_path)%>
</div>
<div>
<%= link_to("Home", root_path)%>
|
<%= link_to("New Post", new_post_path)%>
</div>
<div>
        <% if user_signed_in? %>
        <%= link_to current_user.name,edit_user_path(current_user.id)  %> | 
        <%= link_to "Logout", session_path, method: :delete,
        data: {confirm: 'Are you sure you want to log out?'}
         %>
        <% else %>
        <%= link_to "Login", new_session_path %> |
        <%= link_to "Sign Up", new_user_path %>
        <% end %>
    
</div>
</nav>

blog_on_rails_part2/app/views/shared/_user_form.html.erb
<div class="container d-flex justify-content-center">
    <div class="m-4 p-4 border col-sm-6">
        <%if @flag%>
            <h1 class="text-center">Update Details</h1>
        <%else%>
            <h1 class="text-center">Sign Up</h1>
        <%end%>
    <%= form_with model: @user, :class=>"form-group", local:true do |f|%>
        <% if @user.errors.any? %>
            <p class="text-danger">
                <%= @user.errors.full_messages.join(', ')%>
            </p>
        <% end %>
            <%= f.label :name  %> 
        <div class="input-group mb-2">
            <%= f.text_field :name, :class=>'form-control'%> 
        </div>

            <%= f.label :email  %> 
        <div class="input-group mb-2 ">
            <%= f.email_field :email, :class=>'form-control'%> 
        </div>

        <% if !@flag%>
                <%= f.label :password %>    
            <div class="input-group mb-2">
                <%= f.password_field :password ,:class=>'form-control'%>
            </div>
                <%= f.label :password_confirmation %>
            <div class="input-group mb-2">   
                <%= f.password_field :password_confirmation, :class=>'form-control'%>
            </div>
        <%end%>
        <div class="d-flex justify-content-center">
        <div class="mr-2">
        <%= f.submit :class => 'btn btn-outline-primary mt-4'%>
        </div>
        <div class="ml-2">
        <%= link_to("Cancel", root_path, :class => 'btn btn-outline-primary mt-4')%>
        </div>
        </div>
    <% end %>
    <% if @flag%>
    <div class="text-center"> <%= link_to("Change Password", user_password_path(@user.id))%></div>
    <%end%>

    </div>
</div>